### PR TITLE
 Removes the Claim/Unclaim buttons so that teams cannot claim/unclaim…

### PR DESCRIPTION
**Pull request by betarelease**
… locks and cause confusion about lock ownership

@akshaymankar The idea is to remove the claim/unclaim buttons on el-patron for locks related to releng. Is my commit good enough or should I be deleting lines 57-60 in View.elm as well.

Thanks

Sudhindra.

### CODE REVIEW

**Comment by akshaymankar** [comment]
Do you need to have that text there? It looks like this right now:
screen shot 2018-12-06 at 5 57 01 pm

I think we should just leave the text out. Is it okay if it looks like this?:

screen shot 2018-12-06 at 6 03 21 pm

Also, it would be nice if we could toggle this behaviour somehow because some teams want to claim/unclaim locks. This might require changes on the server side as the client side cannot take any runtime arguments.

**Comment by betarelease** [comment]
Is this app used only for releng-locks or for visualizing other locks as well? If it is used in other places we should add that switch on the server side to toggle on and off. 

Also I dont think we need all the text.. I can fix that.. I was not sure if we should specify.

**Comment by akshaymankar** [comment]
It is used by one other team and they use the buttons. So, we'll need to add the toggle. 

I am thinking we can add the toggle to server side and add change the type of object returned by `/locks` to look something like:
```json
{ 
  "config": {"lockActionsEnabled": true},
  "data": "<currently-returned-object>"
}
```
And the client code can toggle based on the config.

**Comment by akshaymankar** [comment]
Hi @betarelease I have implemented this in this and also deployed it for pks-releng. I ended up creating another endpoint for config and consuming that in the frontend. You can look at this commit if you are interested in the internals: https://github.com/akshaymankar/el-patron/commit/3ddb9dbdcfb059ec5fcbb6718d2fd396c1dfef83

**Pull request closed without merging**
